// Autogenerated by FFIDJI

#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C"
{ 
#endif

typedef char16_t char16;
typedef int8_t int8;
typedef uint8_t uint8;
typedef int16_t int16;
typedef uint16_t uint16;
typedef int32_t int32;
typedef uint32_t uint32;
typedef long int64;
typedef unsigned long uint64;
typedef float float32;
typedef double float64;

__declspec(dllexport) inline void* Alloc_FFI(int32 length)
{ 
    return (void*)malloc(length);
} 

__declspec(dllexport) inline void Free_FFI(void* ptr, int32 length)
{ 
    free(ptr);
} 

struct PairToSum
{ 
    int32 a;
    int32 b;
};

struct ArrayToSum
{ 
    int32* intsToSum_ptr;
    int32 intsToSum_len;
};

struct string
{ 
    char16* utf16_char_ptr;
    int32 utf16_char_len;
};

__declspec(dllexport) int32 Sum(int32 A, int32 B);

#ifdef __cplusplus
} 
#endif
