// Autogenerated by FFIDJI

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{ 
#endif

typedef int8_t int8;
typedef uint8_t uint8;
typedef int16_t int16;
typedef uint16_t uint16;
typedef int32_t int32;
typedef uint32_t uint32;
typedef long int64;
typedef unsigned long uint64;
typedef float float32;
typedef double float64;

struct PairToSum
{ 
    int32 a;
    int32 b;
};

struct ArrayToSum
{ 
    int32* intsToSum_ptr;
    int intsToSum_len;
};

__declspec(dllimport) int32 Sum(int32 A, int32 B);

__declspec(dllimport) int32 SumPair(PairToSum input);

__declspec(dllimport) int32 SumArray(ArrayToSum input);

#ifdef __cplusplus
} 
#endif
