// Autogenerated by FFIDJI

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{ 
#endif

typedef int8_t int8;
typedef uint8_t uint8;
typedef int16_t int16;
typedef uint16_t uint16;
typedef int32_t int32;
typedef uint32_t uint32;
typedef long int64;
typedef unsigned long uint64;
typedef float float32;
typedef double float64;

__declspec(dllimport) int32 Add(int32 A, int32 B);

#ifdef __cplusplus
} 
#endif
